# DL Practical 1
> 19BCE245 - Aayush Shah

# Importing libraries

In [1]:
import math
import numpy as np
import pandas as pd
import seaborn as sns
import statistics as stats
import matplotlib.pyplot as plt
import tensorflow as tf

# Importing dataset

In [2]:
train_dataset = pd.read_csv('../input/titanic/train.csv')
# train_dataset = pd.read_csv('train.csv')
# print('for TRAINING SET : \n',train_dataset)
train_dataset.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [3]:
# test_dataset = pd.read_csv('test.csv')
# test_dataset = pd.read_csv('../input/titanic/test.csv')
# print('for TESTING SET : \n',test_dataset)

# test_dataset = pd.concat(map(pd.read_csv, ['gender_submission.csv', 'test.csv']), ignore_index=True)

test_dataset_X = pd.read_csv('../input/titanic/test.csv')
test_dataset_y = pd.read_csv('../input/titanic/gender_submission.csv')
test_dataset = pd.merge(test_dataset_y,test_dataset_X, on='PassengerId', how='inner')
test_dataset.head(10)
# print(len(test_dataset.values))

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   
5          897         0       3   
6          898         1       3   
7          899         0       2   
8          900         1       3   
9          901         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0   
6                          Connolly, Miss. Kate  female  30.0      0      0   
7                  Caldwell, Mr. Albert Francis    male  26.0      1      1   
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0      0   
9                       Davies, Mr. John Samuel    male  21.0      2      0   

      Ticket     Fare Cabin Embarked  
0     330911   7.8292   NaN        Q  
1     363272   7.0000   NaN        S  
2     240276   9.6875   NaN        Q  
3     315154   8.6625   NaN        S  
4    3101298  12.2875   NaN        S  
5       7538   9.2250   NaN        S  
6     330972   7.6292   NaN        Q  
7     248738  29.0000   NaN        S  
8       2657   7.2292   NaN        C  
9  A/4 48871  24.1500   NaN        S

# Preprocessing

In [4]:
# # Checking `null` values in dataset ; finding null values in columns
print('for TRAINING SET : \n',train_dataset.isnull().sum())
print('\nfor TESTING SET : \n',test_dataset.isnull().sum())

for TRAINING SET : 
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

for TESTING SET : 
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


> Missing values found : 
- training set : age, embarked
- testing set : age, cabin

## Filling missing values

- `Age` : 

In [5]:
train_dataset['Age'].fillna(train_dataset['Age'].mean(), inplace=True)
print('for TRAINING SET : \n',train_dataset.isnull().sum())
test_dataset['Age'].fillna(train_dataset['Age'].mean(), inplace=True)
print('for TRAINING SET : \n',test_dataset.isnull().sum())

for TRAINING SET : 
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
for TRAINING SET : 
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


- `Embarked` : 

In [6]:
train_dataset['Embarked'].fillna(train_dataset['Embarked'].mode()[0], inplace=True)
print('for TRAINING SET : \n',train_dataset.isnull().sum())

for TRAINING SET : 
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64


- `Fare` : 

In [7]:
test_dataset['Fare'].fillna(train_dataset['Fare'].mean(), inplace=True)
print('for TRAINING SET : \n',test_dataset.isnull().sum())

for TRAINING SET : 
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64


> considering only : `PClass`, `Sex`, `Age`, `SibSp`, `Parch`, `Fare`, `Embarked`

In [8]:
X_train = train_dataset.iloc[:,[2,4,5,6,7,9,11]].values
# X_train = train_dataset.iloc[:,[2,4,5,6,7,9,11]]
X_test = test_dataset.iloc[:,[2,4,5,6,7,9,11]].values
# X_test = test_dataset.iloc[:,[1,3,4,5,6,8,10]]
y_train = train_dataset.iloc[:,1].values
# y = train_dataset.iloc[:,1]
y_test = test_dataset.iloc[:,1].values

In [9]:
X_train

array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ...,
       [3, 'female', 29.69911764705882, ..., 2, 23.45, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [10]:
X_test

array([[3, 'male', 34.5, ..., 0, 7.8292, 'Q'],
       [3, 'female', 47.0, ..., 0, 7.0, 'S'],
       [2, 'male', 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       [3, 'male', 38.5, ..., 0, 7.25, 'S'],
       [3, 'male', 29.699117647058763, ..., 0, 8.05, 'S'],
       [3, 'male', 29.699117647058763, ..., 1, 22.3583, 'C']],
      dtype=object)

In [11]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [12]:
y_test

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [13]:
# before encoding : 
print(X_train[0])
print(y_train[0])
print(X_test[0])
print(y_test[0])

[3 'male' 22.0 1 0 7.25 'S']
0
[3 'male' 34.5 0 0 7.8292 'Q']
0


## Encoding categorical data

- encoding `gender` : 

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:, 1] = le.fit_transform(X_train[:, 1])
X_test[:, 1] = le.fit_transform(X_test[:, 1])

In [15]:
# after encoding gender : 
print(X_train[0])
print(y_train[0])
print(X_test[0])
print(y_test[0])

[3 1 22.0 1 0 7.25 'S']
0
[3 1 34.5 0 0 7.8292 'Q']
0


- encoding `Embarked`

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.fit_transform(X_test))

In [17]:
# after encoding embarked : 
print(X_train[0])
print(y_train[0])
print(X_test[0])
print(y_test[0])

[0.0 0.0 1.0 3 1 22.0 1 0 7.25]
0
[0.0 1.0 0.0 3 1 34.5 0 0 7.8292]
0


# Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)   # only transforming to avoid Information Leakage

# Building the ANN

## 1. Initializing ANN

In [19]:
ann = tf.keras.models.Sequential()


User settings:

   KMP_AFFINITY=granularity=fine,noverbose,compact,1,0
   KMP_BLOCKTIME=0
   KMP_DUPLICATE_LIB_OK=True
   KMP_INIT_AT_FORK=FALSE
   KMP_SETTINGS=1
   KMP_WARNINGS=0

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=128
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=true
   KMP_ENABLE_TASK_THROTTLING=true
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER

## 2. Adding theinputlayer and the first hidden layer
- `units` : number of neurons in the layer
- `relu` : rectifier linear unit

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## 3. Adding the second hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## 4. Adding the output layer
- as dimension of the output is 1 *(whether person is survived or not)*
- choosing sigmoid activation as we have binary classification

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

## 1. compiling the ANN
- here we are Updating weights and reducing cost.
- `optimizer` : gradient descent method. Here we are choosing adam as one of the method.
- `loss` : as we are doing binary classification, we'll use binary_crossentropy which will apply CROSS ENTROPY eq.
For non-binary classification use categorical_crossentropy as loss function and softmax as activation function above.
- `metrics` : choosing accuracy. although we can also choose multiple metrices.

In [23]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## 2. Training the ANN on the training set

In [24]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

2022-02-02 19:07:07.086352: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/100
28/28 [==============================] - 1s 3ms/step - loss: 0.6826 - accuracy: 0.6274
Epoch 2/100
28/28 [==============================] - 0s 3ms/step - loss: 0.6625 - accuracy: 0.6633
Epoch 3/100
28/28 [==============================] - 0s 3ms/step - loss: 0.6416 - accuracy: 0.6745
Epoch 4/100
28/28 [==============================] - 0s 3ms/step - loss: 0.6187 - accuracy: 0.6813
Epoch 5/100
28/28 [==============================] - 0s 3ms/step - loss: 0.5976 - accuracy: 0.6970
Epoch 6/100
28/28 [==============================] - 0s 3ms/step - loss: 0.5768 - accuracy: 0.7048
Epoch 7/100
28/28 [==============================] - 0s 3ms/step - loss: 0.5567 - accuracy: 0.7172
Epoch 8/100
28/28 [==============================] - 0s 3ms/step - loss: 0.5378 - accuracy: 0.7441
Epoch 9/100
28/28 [==============================] - 0s 3ms/step - loss: 0.5200 - accuracy: 0.7609
Epoch 10/100
28/28 [==============================] - 0s 2ms/step - loss: 0.5054 - accuracy: 0.7677
Epoch 11/

# Making prediction and Model evaluation
- Prediction

In [25]:
y_pred = (ann.predict(X_test)>0.5)

- Evaluation through metrices

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Confusion Matrix :\n', confusion_matrix(y_test, y_pred))
print('Accuracy Score :', accuracy_score(y_test, y_pred))

Confusion Matrix :
 [[250  16]
 [ 27 125]]
Accuracy Score : 0.8971291866028708


- Making csv file for submission

In [27]:
test_dataset.PassengerId

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [28]:
predictions = []
for i in y_pred:
  if i[0]:
    predictions.append(1)
  else:
    predictions.append(0)
# predictions

In [29]:
# output = pd.DataFrame({"PassengerId": test_dataset.PassengerId, "Survived": predictions})
# print(output)
# output.to_csv('19BCE245_DL_Prac1.csv', index=False)

# Extra models: 

## 1. XGBoost

In [30]:
from xgboost import XGBClassifier   # Similarly for regression, there is a class named as `XGRegressor` 
classifier = XGBClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[19:07:23] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[230  36]
 [ 38 114]]


0.8229665071770335

In [31]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(f"Accuracy: {accuracies.mean()*100:.2f} %")
print(f"Standard Deviation: {accuracies.std()*100:.2f} %")

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[19:07:24] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[19:07:25] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[19:07:26] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[19:07:27] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old be

## 2. CatBoost

In [32]:
!pip install catboost

In [33]:
 from catboost import CatBoostClassifier   # The same CatBoostRegressor is available for Regression.
 classifier = CatBoostClassifier()
 classifier.fit(X_train, y_train)

Learning rate set to 0.009807
0:	learn: 0.6865383	total: 53.8ms	remaining: 53.8s
1:	learn: 0.6806346	total: 55.2ms	remaining: 27.6s
2:	learn: 0.6767701	total: 56.2ms	remaining: 18.7s
3:	learn: 0.6709615	total: 57.7ms	remaining: 14.4s
4:	learn: 0.6650482	total: 59.3ms	remaining: 11.8s
5:	learn: 0.6590147	total: 60.9ms	remaining: 10.1s
6:	learn: 0.6533568	total: 62.3ms	remaining: 8.84s
7:	learn: 0.6478691	total: 63.9ms	remaining: 7.93s
8:	learn: 0.6428664	total: 65ms	remaining: 7.16s
9:	learn: 0.6370185	total: 66.5ms	remaining: 6.58s
10:	learn: 0.6325716	total: 68.2ms	remaining: 6.13s
11:	learn: 0.6281765	total: 69.3ms	remaining: 5.7s
12:	learn: 0.6232064	total: 70.8ms	remaining: 5.37s
13:	learn: 0.6187835	total: 72.3ms	remaining: 5.09s
14:	learn: 0.6137314	total: 73.7ms	remaining: 4.84s
15:	learn: 0.6092345	total: 74.9ms	remaining: 4.61s
16:	learn: 0.6056495	total: 75.8ms	remaining: 4.38s
17:	learn: 0.6004947	total: 77ms	remaining: 4.2s
18:	learn: 0.5964621	total: 78.5ms	remaining: 4.05

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[246  20]
 [ 33 119]]


0.8732057416267942

In [35]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(f"Accuracy: {accuracies.mean()*100:.2f} %")
print(f"Standard Deviation: {accuracies.std()*100:.2f} %")

Learning rate set to 0.009371
0:	learn: 0.6866322	total: 1.2ms	remaining: 1.2s
1:	learn: 0.6803065	total: 4.21ms	remaining: 2.1s
2:	learn: 0.6739883	total: 5.67ms	remaining: 1.89s
3:	learn: 0.6684859	total: 6.69ms	remaining: 1.67s
4:	learn: 0.6638792	total: 7.84ms	remaining: 1.56s
5:	learn: 0.6582615	total: 8.84ms	remaining: 1.46s
6:	learn: 0.6519204	total: 10.6ms	remaining: 1.5s
7:	learn: 0.6472030	total: 11.7ms	remaining: 1.44s
8:	learn: 0.6417917	total: 12.7ms	remaining: 1.4s
9:	learn: 0.6366876	total: 13.7ms	remaining: 1.36s
10:	learn: 0.6310864	total: 14.9ms	remaining: 1.34s
11:	learn: 0.6264440	total: 16.2ms	remaining: 1.33s
12:	learn: 0.6206705	total: 17.8ms	remaining: 1.35s
13:	learn: 0.6162711	total: 19.4ms	remaining: 1.36s
14:	learn: 0.6117522	total: 20.5ms	remaining: 1.35s
15:	learn: 0.6066985	total: 21.8ms	remaining: 1.34s
16:	learn: 0.6021443	total: 23.4ms	remaining: 1.35s
17:	learn: 0.5978724	total: 25.4ms	remaining: 1.38s
18:	learn: 0.5936013	total: 27ms	remaining: 1.39s

# Training various models on the Training set

### 1. Logistic Regression

In [36]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [37]:
y_pred_lr = clf_lr.predict(X_test)

### 2. K-Nearest Neighbor (K-NN)

In [38]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
clf_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [39]:
y_pred_knn = clf_knn.predict(X_test)

### 3. Support Vector Machine (SVM)

In [40]:
from sklearn.svm import SVC
clf_svc = SVC(kernel='linear', random_state=0)
clf_svc.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [41]:
y_pred_svc = clf_svc.predict(X_test)

### 4. Kernel SVM

In [42]:
from sklearn.svm import SVC
clf_kernelSVC = SVC(kernel='rbf', random_state=0)
clf_kernelSVC.fit(X_train, y_train)

SVC(random_state=0)

In [43]:
y_pred_kernelSVC = clf_kernelSVC.predict(X_test)

### 5. Naïve Bayes

In [44]:
from sklearn.naive_bayes import GaussianNB
clf_nb = GaussianNB()
clf_nb.fit(X_train, y_train)

GaussianNB()

In [45]:
y_pred_nb = clf_nb.predict(X_test)

### 6. Decision Tree

  #### 6.1 with **GINI**

In [46]:
from sklearn.tree import DecisionTreeClassifier
clf_dtGINI = DecisionTreeClassifier(criterion='gini',  random_state=0)
clf_dtGINI.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [47]:
y_pred_dtGINI = clf_dtGINI.predict(X_test)

  #### 6.2 with **ENTROPY**

In [48]:
from sklearn.tree import DecisionTreeClassifier
clf_dtENTROPY = DecisionTreeClassifier(criterion='entropy',  random_state=0)
clf_dtENTROPY.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [49]:
y_pred_dtENTROPY = clf_dtENTROPY.predict(X_test)

### 7. Random Forest Classifier

  #### 7.2 with **ENTROPY**

In [50]:
from sklearn.ensemble import RandomForestClassifier
clf_rfcGINI = RandomForestClassifier(n_estimators = 10, criterion = 'gini', random_state = 0)
clf_rfcGINI.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [51]:
y_pred_rfcGINI = clf_rfcGINI.predict(X_test)

  #### 7.2 with **ENTROPY**

In [52]:
from sklearn.ensemble import RandomForestClassifier
clf_rfcENTROPY = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
clf_rfcENTROPY.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [53]:
y_pred_rfcENTROPY = clf_rfcENTROPY.predict(X_test)

### Evaluating the model performance with Confusion Matrix

In [54]:
pip install -U prettytable

  Attempting uninstall: prettytable
    Found existing installation: prettytable 2.4.0
    Uninstalling prettytable-2.4.0:
      Successfully uninstalled prettytable-2.4.0
Note: you may need to restart the kernel to use updated packages.


In [55]:
from prettytable import PrettyTable
from sklearn.metrics import confusion_matrix, accuracy_score

In [56]:
evaluataionTable = PrettyTable()
evaluataionTable.field_names = ["Model", "Confusion Matrix", "Accuracy"]
evaluataionTable.add_row(["Logistic Regression", confusion_matrix(y_test, y_pred_lr), accuracy_score(y_test, y_pred_lr)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["K Nearest Neighbor", confusion_matrix(y_test, y_pred_knn), accuracy_score(y_test, y_pred_knn)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["Support Vector Machine", confusion_matrix(y_test, y_pred_svc), accuracy_score(y_test, y_pred_svc)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["SVM Kernel", confusion_matrix(y_test, y_pred_kernelSVC), accuracy_score(y_test, y_pred_kernelSVC)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["Naïve Bayes", confusion_matrix(y_test, y_pred_nb), accuracy_score(y_test, y_pred_nb)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["Decision Tree (with GINI)", confusion_matrix(y_test, y_pred_dtGINI), accuracy_score(y_test, y_pred_dtGINI)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["Decision Tree (with Entropy)", confusion_matrix(y_test, y_pred_dtENTROPY), accuracy_score(y_test, y_pred_dtENTROPY)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["Random Forest (with GINI)", confusion_matrix(y_test, y_pred_rfcGINI), accuracy_score(y_test, y_pred_rfcGINI)])
evaluataionTable.add_row(["------------------------------", "------------------", "--------------------"])
evaluataionTable.add_row(["Random Forest (with ENTROPY)", confusion_matrix(y_test, y_pred_rfcENTROPY), accuracy_score(y_test, y_pred_rfcENTROPY)])
print(evaluataionTable)

+--------------------------------+--------------------+----------------------+
|             Model              |  Confusion Matrix  |       Accuracy       |
+--------------------------------+--------------------+----------------------+
|      Logistic Regression       |     [[253  13]     |  0.9449760765550239  |
|                                |     [ 10 142]]     |                      |
| ------------------------------ | ------------------ | -------------------- |
|       K Nearest Neighbor       |     [[231  35]     |  0.8588516746411483  |
|                                |     [ 24 128]]     |                      |
| ------------------------------ | ------------------ | -------------------- |
|     Support Vector Machine     |     [[266   0]     |         1.0          |
|                                |     [  0 152]]     |                      |
| ------------------------------ | ------------------ | -------------------- |
|           SVM Kernel           |     [[256  10]   

### Confusion Matrix : 

In [57]:
confusionMatrixTable = PrettyTable()
confusionMatrixTable.field_names = ["Model", "Accuracy"]
confusionMatrixTable.add_row(["Logistic Regression", confusion_matrix(y_test, y_pred_lr)])
confusionMatrixTable.add_row(["K Nearest Neighbor", confusion_matrix(y_test, y_pred_knn)])
confusionMatrixTable.add_row(["Support Vector Machine", confusion_matrix(y_test, y_pred_svc)])
confusionMatrixTable.add_row(["SVM Kernel", confusion_matrix(y_test, y_pred_kernelSVC)])
confusionMatrixTable.add_row(["Naïve Bayes", confusion_matrix(y_test, y_pred_nb)])
confusionMatrixTable.add_row(["Decision Tree (with GINI)", confusion_matrix(y_test, y_pred_dtGINI)])
confusionMatrixTable.add_row(["Decision Tree (with Entropy)", confusion_matrix(y_test, y_pred_dtENTROPY)])
confusionMatrixTable.add_row(["Random Forest (with GINI)", confusion_matrix(y_test, y_pred_rfcGINI)])
confusionMatrixTable.add_row(["Random Forest (with ENTROPY)", confusion_matrix(y_test, y_pred_rfcENTROPY)])
print(confusionMatrixTable)

+------------------------------+-------------+
|            Model             |   Accuracy  |
+------------------------------+-------------+
|     Logistic Regression      |  [[253  13] |
|                              |  [ 10 142]] |
|      K Nearest Neighbor      |  [[231  35] |
|                              |  [ 24 128]] |
|    Support Vector Machine    |  [[266   0] |
|                              |  [  0 152]] |
|          SVM Kernel          |  [[256  10] |
|                              |  [ 31 121]] |
|         Naïve Bayes          |  [[223  43] |
|                              |  [ 12 140]] |
|  Decision Tree (with GINI)   |  [[218  48] |
|                              |  [ 36 116]] |
| Decision Tree (with Entropy) |  [[221  45] |
|                              |  [ 37 115]] |
|  Random Forest (with GINI)   |  [[237  29] |
|                              |  [ 36 116]] |
| Random Forest (with ENTROPY) |  [[234  32] |
|                              |  [ 40 112]] |
+------------

### Accuracy Table : 

In [58]:
AccuracyTable = PrettyTable()
AccuracyTable.field_names = ["Model", "Accuracy"]
AccuracyTable.add_row(["Logistic Regression", accuracy_score(y_test, y_pred_lr)])
AccuracyTable.add_row(["K Nearest Neighbor", accuracy_score(y_test, y_pred_knn)])
AccuracyTable.add_row(["Support Vector Machine", accuracy_score(y_test, y_pred_svc)])
AccuracyTable.add_row(["SVM Kernel", accuracy_score(y_test, y_pred_kernelSVC)])
AccuracyTable.add_row(["Naïve Bayes", accuracy_score(y_test, y_pred_nb)])
AccuracyTable.add_row(["Decision Tree (with GINI)", accuracy_score(y_test, y_pred_dtGINI)])
AccuracyTable.add_row(["Decision Tree (with Entropy)", accuracy_score(y_test, y_pred_dtENTROPY)])
AccuracyTable.add_row(["Random Forest (with GINI)", accuracy_score(y_test, y_pred_rfcGINI)])
AccuracyTable.add_row(["Random Forest (with ENTROPY)", accuracy_score(y_test, y_pred_rfcENTROPY)])
print(AccuracyTable)

+------------------------------+--------------------+
|            Model             |      Accuracy      |
+------------------------------+--------------------+
|     Logistic Regression      | 0.9449760765550239 |
|      K Nearest Neighbor      | 0.8588516746411483 |
|    Support Vector Machine    |        1.0         |
|          SVM Kernel          | 0.9019138755980861 |
|         Naïve Bayes          | 0.868421052631579  |
|  Decision Tree (with GINI)   | 0.7990430622009569 |
| Decision Tree (with Entropy) | 0.8038277511961722 |
|  Random Forest (with GINI)   | 0.8444976076555024 |
| Random Forest (with ENTROPY) | 0.8277511961722488 |
+------------------------------+--------------------+


In [59]:
output = pd.DataFrame({"PassengerId": test_dataset.PassengerId, "Survived": y_pred_kernelSVC})
print(output)
output.to_csv('19BCE245_DL_Prac1_kernelSVC.csv', index=False)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


# Grid Search with SVM
- taking too much load.
> IGNORE THIS SECTION.

In [60]:
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'rbf', random_state = 0)
# classifier.fit(X_train, y_train)

# from sklearn.metrics import confusion_matrix, accuracy_score
# y_pred = classifier.predict(X_test)
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# accuracy_score(y_test, y_pred)

In [61]:
# # k-fold
# from sklearn.model_selection import cross_val_score
# accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)
# print(f"Accuracy : {accuracies.mean()*100:.2f}%")
# print(f"Standard Deviation : {accuracies.std()*100:.2f}%")

In [62]:
# #grid search 
# from sklearn.model_selection import GridSearchCV
# parameters = [
#              {
#                  'C' : np.linspace(0.01, 1,num=10).tolist(),    # [0, 0.25, 0.5, 0.75, 1]
#                  'kernel' : ['linear'],
#                  'degree' : [3, 4, 5],
#              },
#              {
#                  'C' : np.linspace(0.01, 1,num=10).tolist(),    # [0, 0.25, 0.5, 0.75, 1]
#                  'kernel' : ['rbf','poly','sigmoid'],
#                  'gamma' : np.linspace(0.01, 1,num=10).tolist(), # [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
#                  'degree' : [3,4,5],
#              }
#             ]
# grid_search = GridSearchCV(estimator=classifier, 
#                            param_grid=parameters,
#                            scoring='accuracy',  # As we are doing classification, we are using accuracy for scoring models
#                            cv=10, # number of folds (same like k-fold cross validation)
#                            n_jobs=-1 # all your processors will be used available in hardware
#                            )
# grid_search.fit(X_train, y_train)

In [63]:
# #grid search 2 (smaller one)
# from sklearn.model_selection import GridSearchCV
# parameters = [
#             #  {
#             #      'C' :  [0, 0.25, 0.5, 0.75, 1],
#             #      'kernel' : ['linear'],
#             #      'degree' : [3, 4, 5],
#             #  },
#              {
#                  'C' :  [0, 0.3, 0.65, 1],
#                  'kernel' : ['rbf','poly','sigmoid'],
#                  'gamma' :  [0.1,  0.5, 0.9],
#                  'degree' : [3, 4, 5],
#              }
#             ]
# grid_search = GridSearchCV(estimator=classifier, 
#                            param_grid=parameters,
#                            scoring='accuracy',  # As we are doing classification, we are using accuracy for scoring models
#                            cv=4, # number of folds (same like k-fold cross validation)
#                            n_jobs=-1 # all your processors will be used available in hardware
#                            )
# grid_search.fit(X_train, y_train)

In [64]:
# best_accuracy = grid_search.best_score_
# print(f"Best Accuracy achieved : {best_accuracy*100:.2f}%")

In [65]:
# best_parameters = grid_search.best_params_
# print(f"Best parameters achieved : {best_parameters}")