# NLP Practical 3
> 19BCE245 - Aayush Shah

## 1. Explore `CountVectorizer` and `TfidfVectorizer`

  - ### with `CountVectorizer` : 

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [ ]:
corpus = [
  'This is the first document.',
  'This document is the second document.',
  'And this is the third one.',
  'Is this the first document?',
]

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [ ]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2,2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [ ]:
print(X2.toarray())

[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


In [ ]:
vectorizer3 = CountVectorizer(decode_error='ignore', stop_words='english', ngram_range=(1,3))
X3 = vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()

array(['document', 'document second', 'document second document',
       'second', 'second document'], dtype=object)

In [ ]:
print(X3.toarray())

[[1 0 0 0 0]
 [2 1 1 1 1]
 [0 0 0 0 0]
 [1 0 0 0 0]]


  - ### with `TfidfVectorizer` : 

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [ ]:
print(X.shape)
print(vectorizer.get_feature_names_out())
print(X.toarray())

(4, 9)
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


## 2. Do 1st part with file handling.

In [ ]:
# Making files
for i in range(len(corpus)):
  f = open("data"+str(i+1)+".txt", "w")
  f.write(corpus[i])
  f.close()

In [ ]:
# Reading files
extracted_corpus = []
for i in range(len(corpus)):
  f = open("data"+str(i+1)+".txt",'r')
  extracted_corpus.append(f.read())

print(extracted_corpus)

['This is the first document.', 'This document is the second document.', 'And this is the third one.', 'Is this the first document?']


In [ ]:
# Extracting document names from current directory
doc_names = os.listdir('.')
print(doc_names)
doc_names = [i for i in doc_names if ('.txt' in i)]
print(doc_names)

['.config', 'data3.txt', 'data1.txt', 'data4.txt', 'data2.txt', 'sample_data']
['data3.txt', 'data1.txt', 'data4.txt', 'data2.txt']


- ### with `CountVectorizer` : 

In [ ]:
vectorizer4 = CountVectorizer(input=files)
X4 = vectorizer4.fit_transform(corpus)
vectorizer4.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [ ]:
# files = ['data1.txt','data2.txt','data3.txt','data4.txt']

In [ ]:
vectorizer4 = CountVectorizer(input=doc_names)
X4 = vectorizer4.fit_transform(extracted_corpus)
vectorizer4.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [ ]:
print(X4.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
print(X4.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


- ### with `TfidfVectorizer` : 

In [ ]:
vectorizer = TfidfVectorizer(input=doc_names)
X5 = vectorizer.fit_transform(extracted_corpus)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [ ]:
print(X5.shape)
print(vectorizer.get_feature_names_out())
print(X5.toarray())

(4, 9)
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


## 3. Take part in competition 
> [Refer this notebook](https://www.kaggle.com/adamschroeder/countvectorizer-tfidfvectorizer-predict-comments/notebook)