# NLP Practical 4
> 19BCE245 - Aayush Shah

- To Explore and implement Text Preprocessing and Data Representation
(Hint : Sentiment analysis using `Word2Vec` and `Glove` encoding.)

In [3]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

- ## `Word2Vec` : 

In [4]:
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings

warnings.filterwarnings(action = 'ignore')

import gensim
from gensim.models import Word2Vec

# Reading 'shakespeare.txt' file
sample = open("shakespeare.txt", "r")
s = sample.read()

f = s.replace("\n", " ")  # Replacing escape character with space

data = []

for i in sent_tokenize(f):  # iterating through each sentence in the file
	temp = []
	
	for j in word_tokenize(i):  # tokenizing the sentence into words
		temp.append(j.lower())

	data.append(temp)

model1 = gensim.models.Word2Vec(data, min_count = 1,  # Creating CBOW model
							size = 100, window = 5)

print("Cosine similarity between 'dog' " + "and 'keep' - CBOW : ",	model1.similarity('dog', 'keep')) # Printing results
	
print("Cosine similarity between 'king' " +
				"and 'we' - CBOW : ",
	model1.similarity('king', 'we'))

model2 = gensim.models.Word2Vec(data, min_count = 1, size = 100,  # Creating Skip Gram model
											window = 5, sg = 1)

print("Cosine similarity between 'dog' " + "and 'keep' - Skip Gram : ", model2.similarity('dog', 'keep')) # Printing results
	
print("Cosine similarity between 'king' " + "and 'we' - Skip Gram : ", model2.similarity('king', 'we'))

Cosine similarity between 'dog' and 'keep' - CBOW :  0.3822126
Cosine similarity between 'king' and 'we' - CBOW :  0.09798323
Cosine similarity between 'dog' and 'keep' - Skip Gram :  0.4914204
Cosine similarity between 'king' and 'we' - Skip Gram :  0.38389352


#### One-Hot encoding

In [5]:
from sklearn.preprocessing import OneHotEncoder
import itertools

In [6]:
docs = ["I", "love", "dogs", "and", "I", "desperately", "want", "one"]
tokens_docs = [doc.split(" ") for doc in docs]
all_tokens = itertools.chain.from_iterable(tokens_docs)
word_to_id = {token: idx for idx, token in enumerate(set(all_tokens))}

In [7]:
token_ids = [[word_to_id[token] for token in tokens_doc] for tokens_doc in tokens_docs]

In [8]:
vec = OneHotEncoder(categories="auto")
X = vec.fit_transform(token_ids)

In [9]:
print(X.toarray())

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


#### Bag-of-words

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
text = ["i love dogs and i want one"]
vectorizer = CountVectorizer()

In [12]:
vectorizer.fit(text)
print(vectorizer.vocabulary_)

{'love': 2, 'dogs': 1, 'and': 0, 'want': 4, 'one': 3}


In [13]:
vector = vectorizer.transform(text)
print(vector.shape)
print(vector.toarray())

(1, 5)
[[1 1 1 1 1]]


#### TF-IDF representation

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
text1 = ['i love dogs', 'dogs are loyal', 
'golden retriver is my favorite dog breed', 
'i want a dog desperately but i can do nothing']
tf = TfidfVectorizer()
txt_fitted = tf.fit(text1)
txt_transformed = txt_fitted.transform(text1)
print ("The text: ", text1)

The text:  ['i love dogs', 'dogs are loyal', 'golden retriver is my favorite dog breed', 'i want a dog desperately but i can do nothing']


In [16]:
idf = tf.idf_
print(dict(zip(txt_fitted.get_feature_names(), idf)))

{'are': 1.916290731874155, 'breed': 1.916290731874155, 'but': 1.916290731874155, 'can': 1.916290731874155, 'desperately': 1.916290731874155, 'do': 1.916290731874155, 'dog': 1.5108256237659907, 'dogs': 1.5108256237659907, 'favorite': 1.916290731874155, 'golden': 1.916290731874155, 'is': 1.916290731874155, 'love': 1.916290731874155, 'loyal': 1.916290731874155, 'my': 1.916290731874155, 'nothing': 1.916290731874155, 'retriver': 1.916290731874155, 'want': 1.916290731874155}
