## DL Practical 6
> 19BCE245 - Aayush Shah

In [1]:
from tensorflow import keras
import numpy
from numpy import array
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences

In [2]:
data = """ Deep in the festering hold thy father lies,\n   
               of his bones New England pews are made,\n   
               those are altar lights that were his eyes.\n
               What port awaits us, Davy Jones’\n
               or home? I’ve heard of slavers drifting, drifting,\n   
               playthings of wind and storm and chance, their crews\n"""
print("Data:", data, type(data))

data_splitted=data.split('\n') #returns a list of strings
print("Data_Splitted:", data_splitted, type(data_splitted))

tokenizer=Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')

tokenizer.fit_on_texts(data_splitted) #learns a vocabulary 
print("Word Indices:", tokenizer.word_index) #tokenizer.word_index is a dictionary

Data:  Deep in the festering hold thy father lies,
   
               of his bones New England pews are made,
   
               those are altar lights that were his eyes.

               What port awaits us, Davy Jones’

               or home? I’ve heard of slavers drifting, drifting,
   
               playthings of wind and storm and chance, their crews
 <class 'str'>
Data_Splitted: [' Deep in the festering hold thy father lies,', '   ', '               of his bones New England pews are made,', '   ', '               those are altar lights that were his eyes.', '', '               What port awaits us, Davy Jones’', '', '               or home? I’ve heard of slavers drifting, drifting,', '   ', '               playthings of wind and storm and chance, their crews', ''] <class 'list'>
Word Indices: {'of': 1, 'his': 2, 'are': 3, 'drifting': 4, 'and': 5, 'deep': 6, 'in': 7, 'the': 8, 'festering': 9, 'hold': 10, 'thy': 11, 'father': 12, 'lies': 13, 'bones': 14, 'new': 15, 'england': 16, 

In [3]:
vocab_size = len(tokenizer.word_index) + 1
print("Vocab Size:", vocab_size)

sequences=tokenizer.texts_to_sequences(data_splitted) #list of list
l=len(sequences)
print("Sequences:",sequences, type(sequences), l)

Vocab Size: 42
Sequences: [[6, 7, 8, 9, 10, 11, 12, 13], [], [1, 2, 14, 15, 16, 17, 3, 18], [], [19, 3, 20, 21, 22, 23, 2, 24], [], [25, 26, 27, 28, 29, 30], [], [31, 32, 33, 34, 1, 35, 4, 4], [], [36, 1, 37, 5, 38, 5, 39, 40, 41], []] <class 'list'> 12


In [4]:
X=list()
y=list()

for i in range(len(sequences)):
    X.insert(i,sequences[i][:-1]) 
    y.insert(i,sequences[i])

print("X=", X, "y=",y, type(X), type(y))

maxlen = max([len(sequence) for sequence in X])
print("Maxlen:",maxlen)

X= [[6, 7, 8, 9, 10, 11, 12], [], [1, 2, 14, 15, 16, 17, 3], [], [19, 3, 20, 21, 22, 23, 2], [], [25, 26, 27, 28, 29], [], [31, 32, 33, 34, 1, 35, 4], [], [36, 1, 37, 5, 38, 5, 39, 40], []] y= [[6, 7, 8, 9, 10, 11, 12, 13], [], [1, 2, 14, 15, 16, 17, 3, 18], [], [19, 3, 20, 21, 22, 23, 2, 24], [], [25, 26, 27, 28, 29, 30], [], [31, 32, 33, 34, 1, 35, 4, 4], [], [36, 1, 37, 5, 38, 5, 39, 40, 41], []] <class 'list'> <class 'list'>
Maxlen: 8


In [5]:
X=pad_sequences(X,maxlen=maxlen+1,padding='pre') # +1 to have 0 as the first input
print("X:",X, type(X), X.shape)
y=pad_sequences(y,maxlen=maxlen+1,padding='pre')
print("y:",y, type(y), y.shape)

X: [[ 0  0  6  7  8  9 10 11 12]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  1  2 14 15 16 17  3]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0 19  3 20 21 22 23  2]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 25 26 27 28 29]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0 31 32 33 34  1 35  4]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0 36  1 37  5 38  5 39 40]
 [ 0  0  0  0  0  0  0  0  0]] <class 'numpy.ndarray'> (12, 9)
y: [[ 0  6  7  8  9 10 11 12 13]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  1  2 14 15 16 17  3 18]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0 19  3 20 21 22 23  2 24]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25 26 27 28 29 30]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0 31 32 33 34  1 35  4  4]
 [ 0  0  0  0  0  0  0  0  0]
 [36  1 37  5 38  5 39 40 41]
 [ 0  0  0  0  0  0  0  0  0]] <class 'numpy.ndarray'> (12, 9)


In [6]:
y=to_categorical(y,num_classes=vocab_size) 

print("X=", X, "y=",y, type(X), type(y), X.shape, y.shape)

X= [[ 0  0  6  7  8  9 10 11 12]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  1  2 14 15 16 17  3]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0 19  3 20 21 22 23  2]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 25 26 27 28 29]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0 31 32 33 34  1 35  4]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0 36  1 37  5 38  5 39 40]
 [ 0  0  0  0  0  0  0  0  0]] y= [[[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]

In [7]:
model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10))
print(model.output_shape)
model.add(SimpleRNN(units=50, return_sequences=True))
print(model.output_shape)
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()


print("Input Shape of all Layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)
print("Input Dim:",model.layers[0].input_dim)

(None, None, 10)


2022-05-06 14:36:29.939570: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


(None, None, 50)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 10)          420       
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, None, 50)          3050      
_________________________________________________________________
dense (Dense)                (None, None, 42)          2142      
Total params: 5,612
Trainable params: 5,612
Non-trainable params: 0
_________________________________________________________________
Input Shape of all Layers: (None, None) (None, None, 10) (None, None, 50)
Input Dim: 42


In [8]:
model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=['accuracy'])

model.fit(X, y, epochs=200, verbose=0)

2022-05-06 14:36:30.277642: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [9]:
def sample_all_seq_wo_seed(model, tokenizer, n_words, vocab_size): #all the words are sampled
    encoded=list()
    in_text = ''
    # generate a fixed number of words = n_words
    for i in range(n_words):
        # encode the text as integer
        encoded = tokenizer.texts_to_sequences([in_text])[0] # for words not in the vocab it returns []
        print("i:", i, "Encoded:",encoded)
        # pre-pad sequences to a fixed length
        #encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
        encoded.insert(0,0)
        encoded=array(encoded)
        encoded=numpy.reshape(encoded,newshape=(1,-1))
        print("i:", i, "Encoded:",encoded, encoded.shape)
        # predict probability and sample a word from vocab
        if i == 0:
            prob = model.predict(encoded, verbose=0)
            print("i=", i, "Prob:", prob, type(prob), prob.shape)
            yhat=0
            while yhat == 0:
                yhat=numpy.random.choice(range(vocab_size),p=prob.ravel())
            yhat=[yhat]
            yhat=array(yhat)
            yhat=numpy.reshape(yhat,newshape=(1,-1))
            print("i:", i, "If yhat:", yhat, yhat.shape)
        else:
            prob = model.predict(encoded, verbose=0)
            print("i=", i, "Prob:", prob, type(prob), prob.shape)
            yhat=numpy.append(yhat,0)  #just creating space for the next yhat
            yhat=numpy.reshape(yhat,newshape=(1,-1))
            while yhat[0,i] == 0:
                yhat[0,i]=numpy.random.choice(range(vocab_size),p=prob[0,i].ravel())
            print("i:", i, "Else yhat:", yhat, yhat.shape)
        
    
        # map predicted word index to word
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat[0,i]:
                out_word = word
                #print("index:", index, "out_word:", out_word)
                break

        # append to input
        in_text = in_text + out_word + ' '
    return in_text


In [10]:
print("-----------------------sample all seq without seed-----------------------------")
print(sample_all_seq_wo_seed(model, tokenizer, 8, vocab_size))
print("-------------------------------------------------------------------------------")

-----------------------sample all seq without seed-----------------------------
i: 0 Encoded: []
i: 0 Encoded: [[0]] (1, 1)
i= 0 Prob: [[[8.0643690e-01 9.2318133e-03 4.1410034e-03 5.7523265e-03 4.2269784e-03
   6.0244865e-04 2.6597133e-02 2.4160494e-03 3.7575632e-04 1.7523196e-03
   1.2282119e-03 8.0484524e-04 6.1323895e-04 2.4282699e-03 1.1037427e-03
   1.3115929e-03 1.6214408e-03 2.4087643e-03 1.1511584e-03 1.6596120e-02
   1.4385926e-03 3.0712576e-03 2.8903806e-03 9.3258191e-03 1.4952599e-03
   8.7563479e-03 2.7778975e-03 2.3075461e-03 2.0957375e-03 2.1558350e-03
   8.2405342e-04 1.7763002e-02 5.5762017e-03 2.0091517e-03 3.4940555e-03
   7.4961683e-04 3.1205000e-02 2.7203362e-04 1.1279900e-03 3.4603304e-03
   4.8816497e-03 1.5223001e-03]]] <class 'numpy.ndarray'> (1, 1, 42)
i: 0 If yhat: [[36]] (1, 1)
i: 1 Encoded: [36]
i: 1 Encoded: [[ 0 36]] (1, 2)
i= 1 Prob: [[[8.0643678e-01 9.2318160e-03 4.1410048e-03 5.7523283e-03 4.2269798e-03
   6.0244859e-04 2.6597140e-02 2.4160501e-03 3.757

In [11]:
def prob_of_input_sentence(model, tokenizer, sentence):
    print("Input Sentence:", sentence)
    encoded=tokenizer.texts_to_sequences([sentence])[0]
    print("encoded before insert:", encoded)
    encoded.insert(0,0)
    encoded=array(encoded)
    encoded=numpy.reshape(encoded,newshape=(1,-1))
    print("Encoded:", encoded, encoded.shape)
    prob=model.predict(encoded, verbose=0)
    print("Prob:", prob, prob.shape)
    probability=1
    for i in range(prob.shape[1]-1):
        probability = probability * prob[0,i,encoded[0,i+1]]
    print("Probability of Sentence", "\"", sentence, "\"", "is:", probability)

In [12]:
print("-------------------Probability of Input Sentence------------------------------")  
prob_of_input_sentence(model, tokenizer, "Deep in the festering")
prob_of_input_sentence(model, tokenizer, "lights that were his nose")
prob_of_input_sentence(model, tokenizer, "lights that were his")
prob_of_input_sentence(model, tokenizer, "gone blind, the")
print("-------------------------------------------------------------------------------")

-------------------Probability of Input Sentence------------------------------
Input Sentence: Deep in the festering
encoded before insert: [6, 7, 8, 9]
Encoded: [[0 6 7 8 9]] (1, 5)
Prob: [[[8.06436896e-01 9.23181325e-03 4.14100336e-03 5.75232645e-03
   4.22697840e-03 6.02448650e-04 2.65971329e-02 2.41604936e-03
   3.75756325e-04 1.75231963e-03 1.22821191e-03 8.04845244e-04
   6.13238954e-04 2.42826995e-03 1.10374275e-03 1.31159287e-03
   1.62144075e-03 2.40876433e-03 1.15115836e-03 1.65961199e-02
   1.43859256e-03 3.07125761e-03 2.89038057e-03 9.32581909e-03
   1.49525993e-03 8.75634793e-03 2.77789752e-03 2.30754609e-03
   2.09573749e-03 2.15583504e-03 8.24053423e-04 1.77630018e-02
   5.57620171e-03 2.00915174e-03 3.49405548e-03 7.49616825e-04
   3.12050004e-02 2.72033620e-04 1.12798996e-03 3.46033042e-03
   4.88164974e-03 1.52230007e-03]
  [1.99159831e-02 5.91844022e-01 6.50484487e-02 4.46971171e-02
   2.05279351e-03 2.66148127e-04 3.10377534e-02 2.88281012e-02
   1.06187863e-03 2.7